### ISSUE TITLE
Show available ships

### ISSUE THREAD

**Issue by christofjens** [christofjens/capstone-project#19]
# Value Proposition
As a **user**
I want to **see available loans**
in order to **to buy a ship**

# Description (text, scribble, wireframe, design

# Acceptance criteria
- [x] Shows available loans
- [x] Take loan
- [ ] If successful, show success message
- [x] If not successful, show error message

# Complexity (low, medium, high)
low

# Tasks
- [x] Create feature branch
- [x] Write test for component
- [x] Build component
