### ISSUE TITLE
Show list of own ships

### ISSUE THREAD

**Issue by christofjens** [christofjens/capstone-project#24]
# Value Proposition
As a **user**
I want to **see my ships**
in order to **to give them orders**

# Description (text, scribble, wireframe, design

# Acceptance criteria
- [ ] Shows my ships

# Complexity (low, medium, high)
low

# Tasks
- [ ] Create feature branch
- [ ] Write test for component
- [ ] Build component
