### ISSUE TITLE
# Value Proposition

### ISSUE THREAD

**Issue by christofjens** [christofjens/capstone-project#26]
As a **user**
I want to **see the objects in the system**
in order to **travel there**

# Description (text, scribble, wireframe, design

# Acceptance criteria
- [ ] Shows an overview of the objects fetched from the API

# Complexity (low, medium, high)
low

# Tasks
- [x] Create feature branch
- [ ] Write test for component
- [x] Build component
