### ISSUE TITLE
Show system object detail

### ISSUE THREAD

**Issue by christofjens** [christofjens/capstone-project#27]
# Value Proposition
As a **user**
I want to **see see all objects in the system**
in order to **travel there**

# Description (text, scribble, wireframe, design

# Acceptance criteria
- [x] Shows objects in the system, fetched from API

# Complexity (low, medium, high)
low

# Tasks
- [x] Create feature branch
- [ ] Write test for component
- [x] Build component
